### ISSUE TITLE
error when face tracking

### ISSUE THREAD

**Issue by SavageVic** [Fictionarry/ER-NeRF#114]
(ernerf) root@autodl-container-ea5a488e8d-86f88d50:/home/aigc/ER-NeRF# python data_utils/process.py data/vic/vic.mp4 --task 8
[INFO] ===== perform face tracking =====
Traceback (most recent call last):
  File "/home/aigc/ER-NeRF/data_utils/face_tracking/face_tracker.py", line 11, in <module>
    from render_3dmm import Render_3DMM
  File "/home/aigc/ER-NeRF/data_utils/face_tracking/render_3dmm.py", line 6, in <module>
    from pytorch3d.renderer import (
  File "/root/miniconda3/envs/ernerf/lib/python3.10/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/root/miniconda3/envs/ernerf/lib/python3.10/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory
[INFO] ===== finished face tracking =====

how to fix it?

thanks a million

**Comment by SavageVic** [comment]
I checked cuda not avaialbe.
I turned to  the cloud server customer support, he shared that there is a bug when installing pytorch with conda,   he suggested to use pip to install pytorch.

**Comment by zzy419** [comment]
I used pip to install pytorch but can't fix it.
