### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by cheng0009** [Fictionarry/ER-NeRF#136]
How did this error arise? How should we handle it?

The error message is as follows:

loading data: 100%|█████████████████████████████████████████████████████████████████| 335/335 [00:01<00:00, 213.51it/s]
[INFO] fitting focal length...
600 2.325517177581787 -3.084073305130005
700 2.324472427368164 -3.6350789070129395
800 2.308330535888672 -4.123293399810791
900 2.3155314922332764 -4.684905052185059
1000 2.3085672855377197 -5.217588424682617
1100 2.308321475982666 -5.755466938018799
1200 2.3131892681121826 -6.298212051391602
1300 2.3034346103668213 -6.784102916717529
1400 2.3235983848571777 -7.447474002838135
[INFO] find best focal: 1300
[INFO] coarse fitting...
2.6580092906951904 -7.539440631866455
[INFO] fitting light...
Traceback (most recent call last):
  File "E:\ernerf\avatar_ernerf\create_train_task.py", line 145, in <module>
    train(args)
  File "E:\ernerf\avatar_ernerf\create_train_task.py", line 98, in train
    processor(
  File "E:\ernerf\avatar_ernerf\processor.py", line 78, in processor
    model_cfg_file = preprocess_tasks(
  File "E:\ernerf\avatar_ernerf\tasks\preprocess.py", line 1146, in preprocess_tasks
    run_face_tracking(input_dir=ori_imgs_dir)
  File "E:\ernerf\avatar_ernerf\tasks\preprocess.py", line 819, in run_face_tracking
    face_tracker_training(
  File "E:\ernerf\avatar_ernerf\modules\face_tracking\face_tracker_new.py", line 225, in face_tracker_training
    render_imgs = renderer(
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ernerf\avatar_ernerf\modules\face_tracking\render_3dmm.py", line 189, in forward
    rendered_img = self.renderer(mesh)
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\pytorch3d\renderer\mesh\renderer.py", line 61, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\pytorch3d\renderer\mesh\rasterizer.py", line 252, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\pytorch3d\renderer\mesh\rasterize_meshes.py", line 223, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\torch\autograd\function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\Aconda3\envs\avatar_ernerf\lib\site-packages\pytorch3d\renderer\mesh\rasterize_meshes.py", line 297, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

How did this error arise? How should we handle it? please！

**Comment by DestoryVIP** [comment]
uninstall the pytorch3d, and shencoder, freqencoder, gridencoder, raymarching, shencoder， you can fix it. Good Luck

**Comment by DestoryVIP** [comment]
> uninstall the pytorch3d, and shencoder, freqencoder, gridencoder, raymarching, shencoder， you can fix it. Good Luck卸载pytorch3d，和shencoder，freqencoder，gridencoder，raymarching，shencoder，你可以修复它。祝你好运

and reinstall these package
