### ISSUE TITLE
This error may appear if the input matrix contains NaN.

### ISSUE THREAD

**Issue by skyz8421** [Fictionarry/ER-NeRF#14]
`$: python3 main.py data/obama/ --workspace trial_obama_torso/ -O --torso --head_ckpt trial_obama/checkpoints/ngp_ep0017.pth --iters 200000`

```
.....
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/root/miniconda3/envs/ernerf/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/root/miniconda3/envs/ernerf/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /root/miniconda3/envs/ernerf/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /root/miniconda3/envs/ernerf/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
[INFO] Trainer: ngp | 2023-08-07_10-52-06 | cuda | fp16 | trial_obama_torso/
[INFO] #parameters: 1199692
[INFO] Loading latest checkpoint ...
[WARN] No checkpoint found, model randomly initialized.
[INFO] load 100 val frames.
[INFO] load  aud_features: torch.Size([7999, 29, 16])
Loading val data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1713.70it/s]
[INFO] eye_area: 0.0 - 0.8100000023841858
[INFO] max_epoch = 28
==> Start Training Epoch 1, lr=0.010000 ...
  0% 0/7272 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/bd/yzx-lq/workspace/ER-NeRF/main.py", line 248, in <module>
    trainer.train(train_loader, valid_loader, max_epochs)
  File "/mnt/bd/yzx-lq/workspace/ER-NeRF/nerf_triplane/utils.py", line 976, in train
    self.train_one_epoch(train_loader)
  File "/mnt/bd/yzx-lq/workspace/ER-NeRF/nerf_triplane/utils.py", line 1234, in train_one_epoch
    self.model.update_extra_state()
  File "/root/miniconda3/envs/ernerf/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/bd/yzx-lq/workspace/ER-NeRF/nerf_triplane/renderer.py", line 516, in update_extra_state
    alphas, _, _ = self.forward_torso(xys, pose, ind_code) # [N, 1]
  File "/mnt/bd/yzx-lq/workspace/ER-NeRF/nerf_triplane/network.py", line 175, in forward_torso
    wrapped_anchor = self.anchor_points[None, ...] @ poses.permute(0, 2, 1).inverse()
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`. This error may appear if the input matrix contains NaN.
  0% 0/7272 [00:01<?, ?it/s]
```
  
  When I tried to run the training code, it returned the error above. 
  It seems that there are NaN in the input matrix? How can I fix this error?

**Comment by Eikwang** [comment]
应该是第一步训练头部的问题，我也遇到过，重新训练吧
