### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by jackysong2009** [Fictionarry/ER-NeRF#147]
win11系统，conda下，执行pip install ./raycharming 成功
(Vach) PS D:\Metahuman\Vach\talkers\er_nerf> pip install ./raymarching
Processing d:\metahuman\vach\talkers\er_nerf\raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching_face
  Building wheel for raymarching_face (setup.py) ... done
  Created wheel for raymarching_face: filename=raymarching_face-0.0.0-cp310-cp310-win_amd64.whl size=241161 sha256=975cbbd0f453096e034705309d403ec62fd157f790de53e41c78eedac9a4aec0
  Stored in directory: C:\Users\15833\AppData\Local\Temp\pip-ephem-wheel-cache-oprdbt9n\wheels\bb\6d\52\19643e7715cd22b429ac110109e8eabf1f49d338db50bb6625
Successfully built raymarching_face
Installing collected packages: raymarching_face
  Attempting uninstall: raymarching_face
    Found existing installation: raymarching_face 0.0.0
    Uninstalling raymarching_face-0.0.0:
      Successfully uninstalled raymarching_face-0.0.0
Successfully installed raymarching_face-0.0.0
但是执行训练的时候报错
(Vach) PS D:\Metahuman\Vach\talkers\er_nerf> python main.py data/obama/ --workspace trial_obama/ -O --test --ckpt trial_obama/checkpoints/ngp.pth
Traceback (most recent call last):
  File "D:\Metahuman\Vach\talkers\er_nerf\main.py", line 6, in <module>
    from nerf_triplane.network import NeRFNetwork
  File "D:\Metahuman\Vach\talkers\er_nerf\nerf_triplane\network.py", line 5, in <module>
    from .renderer import NeRFRenderer
  File "D:\Metahuman\Vach\talkers\er_nerf\nerf_triplane\renderer.py", line 10, in <module>
    from .. import raymarching
ImportError: attempted relative import beyond top-level package

**Comment by cacard** [comment]
windows环境不好说，建议win+wsl，根据cuda版本组合好python/torch/cuda/pytorch3d的版本。

**Comment by xiaomaofei** [comment]
我也是相同的问题。我也是训练出了问题。 0% 0/7272 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\Datemanwf\Test\ER-NeRF-main\main.py", line 248, in <module>
    trainer.train(train_loader, valid_loader, max_epochs)
  File "E:\Datemanwf\Test\ER-NeRF-main\nerf_triplane\utils.py", line 983, in train
    self.train_one_epoch(train_loader)
  File "E:\Datemanwf\Test\ER-NeRF-main\nerf_triplane\utils.py", line 1241, in train_one_epoch
    self.model.update_extra_state()
  File "D:\anaconda\envs\py39\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
