### ISSUE TITLE
执行视频预处理的时候，提取面部特征报错

### ISSUE THREAD

**Issue by Ivyforever01** [Fictionarry/ER-NeRF#156]
Traceback (most recent call last):
  File "/root/autodl-tmp/ER-NeRF/data_utils/process.py", line 52, in extract_landmarks
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False)
  File "/root/miniconda3/envs/ernerf/lib/python3.10/site-packages/face_alignment/api.py", line 87, in __init__
    self.face_alignment_net = torch.jit.load(
  File "/root/miniconda3/envs/ernerf/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
有没有大佬知道这个问题，请教一下
![1721180940430](https://github.com/user-attachments/assets/a65f53a0-f032-4e03-ab0e-2969700a388e)

**Comment by zhangshulin12** [comment]
我也遇到这个错误，你解决了吗
