### ISSUE TITLE
Traceback有问题，前面都是正确的，但是python main.py data/ --workspace trial_obama/ -O --iters 100000运行错误

### ISSUE THREAD

**Issue by xiaomaofei** [Fictionarry/ER-NeRF#157]
Traceback (most recent call last):
  File "E:\Datemanwf\Test\ER-NeRF-main\main.py", line 248, in <module>
    trainer.train(train_loader, valid_loader, max_epochs)
  File "E:\Datemanwf\Test\ER-NeRF-main\nerf_triplane\utils.py", line 983, in train
    self.train_one_epoch(train_loader)
  File "E:\Datemanwf\Test\ER-NeRF-main\nerf_triplane\utils.py", line 1241, in train_one_epoch
    self.model.update_extra_state()
  File "D:\anaconda\envs\py39\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Datemanwf\Test\ER-NeRF-main\nerf_triplane\renderer.py", line 469, in update_extra_state
    sigmas = self.density(cas_xyzs, enc_a, eye)['sigma'].reshape(-1).detach().to(tmp_grid.dtype)

**Comment by liyao1520** [comment]
> xiaomaofei

解决了吗？

**Comment by xiaomaofei** [comment]
全部解决了。我在linux上运行都没问题，对应cuda和troch的版本都对应好，没什么问题了

**Comment by xwqlikepsl** [comment]
老哥用的什么版本的呀
