### ISSUE TITLE
训练时候遇到以下报错，怎么解决

### ISSUE THREAD

**Issue by zhangshulin12** [Fictionarry/ER-NeRF#159]
Traceback (most recent call last):
  File "E:\oyh\ER-NeRF-main\data_utils\face_parsing\test.py", line 98, in <module>
    evaluate(respth=args.respath, dspth=args.imgpath, cp=args.modelpath)
  File "E:\oyh\ER-NeRF-main\data_utils\face_parsing\test.py", line 62, in evaluate
    net.load_state_dict(torch.load(cp))
  File "E:\oyh\Anaconda\envs\nerfstream\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\oyh\Anaconda\envs\nerfstream\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\oyh\Anaconda\envs\nerfstream\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data_utils/face_parsing/79999_iter.pth'
[INFO] ===== extracted semantics =====
[INFO] ===== extract background image from E:/oyh/ER-NeRF-main/data/xuniren\ori_imgs =====
  0%|                                                                                                                                | 0/95 [00:00<?, ?it/s][ WARN:0@737.110] global loadsave.cpp:241 cv::findDecoder imread_('E:/oyh/ER-NeRF-main/data/xuniren\parsing\0.png'): can't open/read file: check file path/integrity
  0%|                                                                                                                                | 0/95 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\oyh\ER-NeRF-main\data_utils\process.py", line 388, in <module>
    extract_background(base_dir, ori_imgs_dir)
  File "E:\oyh\ER-NeRF-main\data_utils\process.py", line 84, in extract_background
    bg = (parse_img[..., 0] == 255) & (parse_img[..., 1] == 255) & (parse_img[..., 2] == 255)
TypeError: 'NoneType' object is not subscriptable

**Comment by kiligzn** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by cunning-program-ape** [comment]
我也遇到了

**Comment by dedededede** [comment]
检查一下model的完整性，最好自己离线下载替换到目标文件夹

**Comment by tianzhuoli11** [comment]
你得先下载79999_iter.pth这个文件吧，第二个问题换一个环境试一试
