### ISSUE TITLE
IndexError in training : IndexError: index 518 is out of bounds for axis 0 with size 518

### ISSUE THREAD

**Issue by amamrnaf** [Fictionarry/ER-NeRF#170]
python3 main.py data/obama/ --workspace trial_obama/ -O --iters 100000
Namespace(path='data/obama/', O=True, test=False, test_train=False, data_range=[0, -1], workspace='trial_obama/', seed=0, iters=100000, lr=0.01, lr_net=0.001, ckpt='latest', num_rays=65536, cuda_ray=True, max_steps=16, num_steps=16, upsample_steps=0, update_extra_interval=16, max_ray_batch=4096, warmup_step=10000, amb_aud_loss=1, amb_eye_loss=1, unc_loss=1, lambda_amb=0.0001, fp16=True, bg_img='', fbg=False, exp_eye=True, fix_eye=-1, smooth_eye=False, torso_shrink=0.8, color_space='srgb', preload=0, bound=1, scale=4, offset=[0, 0, 0], dt_gamma=0.00390625, min_near=0.05, density_thresh=10, density_thresh_torso=0.01, patch_size=1, init_lips=False, finetune_lips=False, smooth_lips=False, torso=False, head_ckpt='', gui=False, W=450, H=450, radius=3.35, fovy=21.24, max_spp=1, att=2, aud='', emb=False, ind_dim=4, ind_num=10000, ind_dim_torso=8, amb_dim=2, part=False, part2=False, train_camera=False, smooth_path=False, smooth_path_window=7, asr=False, asr_wav='', asr_play=False, asr_model='deepspeech', asr_save_feats=False, fps=50, l=10, m=50, r=10)
[INFO] load 7272 train frames.
[INFO] load  aud_features: torch.Size([7999, 29, 16])
Loading train data:   7%|██████████▍                                                                                                                                        | 518/7272 [00:00<00:01, 4712.77it/s]
Traceback (most recent call last):
  File "/home/ubuntu/ER-NeRF/main.py", line 218, in <module>
    train_loader = NeRFDataset(opt, device=device, type='train').dataloader()
  File "/home/ubuntu/ER-NeRF/nerf_triplane/provider.py", line 500, in __init__
    area = au_blink[f['img_id']]
IndexError: index 518 is out of bounds for axis 0 with size 518

**Comment by frankjiang** [comment]
same error

**Comment by amamrnaf** [comment]
> same error

i fixed it , re do the face extraction for the training video and wait a while , even when the file shows up its not full yet ,
