### ISSUE TITLE
IndexError: index 3327 is out of bounds for axis 0 with size 3327

### ISSUE THREAD

**Issue by mrhanCH** [Fictionarry/ER-NeRF#50]
[INFO] Trainer: ngp | 2023-09-27_19-40-14 | cuda | fp16 | trial_t2/
[INFO] #parameters: 683509
[INFO] Loading latest checkpoint ...
[INFO] Latest checkpoint is trial_t2/checkpoints/ngp_ep0042.pth
[INFO] loaded model.
[INFO] load at epoch 42, global step 127134
[INFO] loaded optimizer.
[INFO] loaded scheduler.
[INFO] loaded scaler.
[INFO] load 100 val frames.
[INFO] load  aud_features: torch.Size([3325, 1024, 2])
Loading val data: 100%|███████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 3601.65it/s]
[INFO] eye_area: 0.0 - 1.0
[INFO] max_epoch = 42
[INFO] load 303 test frames.
[INFO] load  aud_features: torch.Size([3325, 1024, 2])
Loading test data:  99%|█████████████████████████████████████████████████████████████████████████████████████▏| 300/303 [00:00<00:00, 3633.58it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/ER-NeRF/main.py", line 257, in <module>
    test_loader = NeRFDataset(opt, device=device, type='test').dataloader()
  File "/root/autodl-tmp/ER-NeRF/nerf_triplane/provider.py", line 500, in __init__
    area = au_blink[f['img_id']]
IndexError: index 3327 is out of bounds for axis 0 with size 3327

你好，感谢你们的工作和分享，我在使用一个2分钟多的视频进行训练时，当进行测试集加载时就报上面的错误，请问这是哪里的问题，感谢！

**Comment by Fictionarry** [comment]
检查一下au.csv和ffmpeg抽取的帧数是否相等，问题可能跟视频的编码或者帧率有关

**Comment by SanBingYouYong** [comment]
是的, 如果视频帧率不是25帧(`ffmpeg -i <video>.mp4`)就会出现这种问题, 参考[这里](https://trac.ffmpeg.org/wiki/ChangingFrameRate)用ffmpeg重新编码视频到25帧然后重新处理(包括OpenFace Feature Extraction)即可

**Comment by chenkai89** [comment]
我也是这个问题，我是使用官方obama.mp4 这个视频进行训练，au.csv 这个文件有635行数据，gt_imgs 则有8000张图片。
我也使用 ffmpeg -i obama.mp4 -r 25 output.mp4 进行转换还是一样的错误
