### ISSUE TITLE
No such file or directory: 'data/obama/track_params.pt'

### ISSUE THREAD

**Issue by liushifu12138** [Fictionarry/ER-NeRF#57]
pytorch3d == 0.7.4
python  == 3.10.13 
torch == 2.1.0
[INFO] ===== finished face tracking =====
[INFO] ===== save transforms =====

[INFO] fitting light...
Traceback (most recent call last):
  File "/home/xiaoduo/liu/ER-NeRF-main/data_utils/face_tracking/face_tracker.py", line 219, in <module>
    render_imgs = renderer(
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaoduo/liu/ER-NeRF-main/data_utils/face_tracking/render_3dmm.py", line 199, in forward
    rendered_img = self.renderer(mesh)
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/pytorch3d/renderer/mesh/renderer.py", line 62, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaoduo/liu/ER-NeRF-main/data_utils/face_tracking/render_3dmm.py", line 73, in forward
    images = softmax_rgb_blend(
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/pytorch3d/renderer/blending.py", line 205, in softmax_rgb_blend
    alpha = torch.prod((1.0 - prob_map), dim=-1)
RuntimeError: 
  #define POS_INFINITY __int_as_float(0x7f800000)
  #define INFINITY POS_INFINITY
  #define NEG_INFINITY __int_as_float(0xff800000)
  #define NAN __int_as_float(0x7fffffff)

Traceback (most recent call last):
  File "/home/xiaoduo/liu/ER-NeRF-main/data_utils/process.py", line 407, in <module>
    save_transforms(base_dir, ori_imgs_dir)
  File "/home/xiaoduo/liu/ER-NeRF-main/data_utils/process.py", line 276, in save_transforms
    params_dict = torch.load(os.path.join(base_dir, 'track_params.pt'))
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xiaoduo/miniconda3/envs/nerf/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/obama/track_params.pt'

**Comment by Fictionarry** [comment]
Seems some errors have occurred in the function `face_tracking`. Please check this step

**Comment by Fictionarry** [comment]
refer to issue https://github.com/Fictionarry/ER-NeRF/issues/31
