### ISSUE TITLE
nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by liushifu12138** [Fictionarry/ER-NeRF#62]
[INFO] ===== extract face landmarks from data/obama/ori_imgs =====
  0%|                                                                                                      | 1/8000 [00:07<17:43:43,  7.98s/it]
Traceback (most recent call last):
  File "data_utils/process.py", line 399, in <module>
    extract_landmarks(ori_imgs_dir)
  File "data_utils/process.py", line 61, in extract_landmarks
    preds = fa.get_landmarks(input)
  File "/home/xiaoduo/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/face_alignment/api.py", line 113, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces, return_bboxes, return_landmark_score)
  File "/home/xiaoduo/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/xiaoduo/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/face_alignment/api.py", line 168, in get_landmarks_from_image
    out = self.face_alignment_net(inp).detach()
  File "/home/xiaoduo/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

Python 3.8.18

**Comment by jinqiupeter** [comment]
You probably use Lovelace/Hopper GPUs like RTX 40 series or H100/H800, they are not compatible with the CUDA version being used. 

Try the previous generation like RTX 3090.

**Comment by ThetaRgo** [comment]
how to solve this?

**Comment by h-oneohone** [comment]
Have you solved it yet?
